name: C++ CI with Makefile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev

      - name: Build main executable
        run: |
          make main

      - name: Build and run tests
        run: |
          make tests

      - name: Clean all
        run: |
          make cleanall
